vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        projects_pictures:
            uri_prefix: /uploads/images/projects
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
